name: Deploy AI

on:
  push:
    branches:
      - release-*
  pull_request:
    branches:
      - release-*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Build and tag Docker image 1
      uses: docker/build-push-action@v2
      with:
        context: ./Filtrado
        push: true
        tags: |
          ebloemer/diagnostic-ia1:${{ github.sha }}

    - name: Build and tag Docker image 2
      uses: docker/build-push-action@v2
      with:
        context: ./Informe
        push: true
        tags: |
          ebloemer/diagnostic-ia2:${{ github.sha }}

    - name: Deploy to DigitalOcean Droplet
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.DROPLET_HOST }}
        username: ${{ secrets.DROPLET_USER }}
        password: ${{ secrets.DROPLET_PASSWORD }}
        script: |
          /home/ia/ia-cicd.sh ${{ github.sha }}
